### ISSUE TITLE
ST4下颜色不起作用

### ISSUE THREAD

**Issue by tortoo** [cj1128/sublime-buildx#1]
作者您好，安装后遇到一些问题，特来请教哈。控制台可以在双栏右侧，很完美。但我这里颜色不起作用，弹窗提示"Error loading syntax file "Packages/BuildX/BuildX.sublime-syntax": Unable to read Packages/BuildX/BuildX.sublime-syntax"，我是ST4，不知道是否和版本有关。另外参照usage设置了super+b和super+shift+b快捷键，但没发现两个的区别

**Comment by cj1128** [comment]
ST4 我在官网没有看到下载链接，你可以贴下链接吗？我下载下来测试一下。

你也可以用 ST3 来试试这个插件，我这边一直在用，是没有问题的。

至于 `super+b` 和 `super+shift+b` 的区别，`super+b` 运行上次选择的 Build Variant，而 `super+shift+b` 会弹出 Build Variants 列表供你选择。

因为某些文件会配置多个 Build Variants，比如 C，按 `super+shift+b` 时会弹出如下列表：

![image](https://user-images.githubusercontent.com/4210829/106615427-626a2780-65a7-11eb-914f-8e2db23633a5.png)

**Comment by tortoo** [comment]
你也装4吧，毕竟4是趋势😹。我用的4088，目前相对稳定的版本。[提取: gwiw](https://pan.baidu.com/s/19TBxlEURFx77pFAAUbej3Q)
不知方便加q不？

**Comment by tortoo** [comment]
抱歉又来打扰……之前我用ST4 4088版很正常，启动也没有报错信息。昨天更新了4100版，结果启动时报错，如下：

```
reloading python 3.3 plugin BuildX.ansi
reloading python 3.3 plugin BuildX.buildx
reloading python 3.3 plugin BuildX.test-color-scheme
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1661, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/BuildX.sublime-package/test-color-scheme.py", line 5
    print(f"\x1b[0m\x1b[{code}m{name}\x1b[0m")
                                            ^
SyntaxError: invalid syntax
```

编译时报错：

`__init__() got an unexpected keyword argument 'kill_previous'`

今天又出了4101版，结果情况和4100一样，上面两处仍然报错

我又装回4088，启动时控制台仍然报错，和上面一样。编译时却正常输出

 [ 4100版 提取：hryv](https://pan.baidu.com/s/1kd6-0CYHEMYQBZloIOYPyw)

**Comment by tortoo** [comment]
完美解决了！我删掉了Default文件夹，重启后它会自动重建，然后build的问题都没了，启动时BuildX的报错也消失了😸！棒棒哒！
