### ISSUE TITLE
Invalid syntax error on startup

### ISSUE THREAD

**Issue by z-aki** [cj1128/sublime-buildx#2]
ST 4113
BuildX 1.1.0
```
Traceback (most recent call last):
  File "/Users/t/apps/SublimeText.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Users/t/apps/SublimeText.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/t/Library/Application Support/Sublime Text/Installed Packages/BuildX.sublime-package/test-color-scheme.py", line 5
    print(f"\x1b[0m\x1b[{code}m{name}\x1b[0m")
                                            ^
SyntaxError: invalid syntax
```

**Comment by cj1128** [comment]
Fixed, thank you.
